# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/compiler/CMakeFiles /root/compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

BackEnd/KoopaWalker.o: BackEnd/KoopaWalker.cpp.o

.PHONY : BackEnd/KoopaWalker.o

# target to build an object file
BackEnd/KoopaWalker.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/KoopaWalker.cpp.o
.PHONY : BackEnd/KoopaWalker.cpp.o

BackEnd/KoopaWalker.i: BackEnd/KoopaWalker.cpp.i

.PHONY : BackEnd/KoopaWalker.i

# target to preprocess a source file
BackEnd/KoopaWalker.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/KoopaWalker.cpp.i
.PHONY : BackEnd/KoopaWalker.cpp.i

BackEnd/KoopaWalker.s: BackEnd/KoopaWalker.cpp.s

.PHONY : BackEnd/KoopaWalker.s

# target to generate assembly for a file
BackEnd/KoopaWalker.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/KoopaWalker.cpp.s
.PHONY : BackEnd/KoopaWalker.cpp.s

BackEnd/RegisterAllocator.o: BackEnd/RegisterAllocator.cpp.o

.PHONY : BackEnd/RegisterAllocator.o

# target to build an object file
BackEnd/RegisterAllocator.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/RegisterAllocator.cpp.o
.PHONY : BackEnd/RegisterAllocator.cpp.o

BackEnd/RegisterAllocator.i: BackEnd/RegisterAllocator.cpp.i

.PHONY : BackEnd/RegisterAllocator.i

# target to preprocess a source file
BackEnd/RegisterAllocator.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/RegisterAllocator.cpp.i
.PHONY : BackEnd/RegisterAllocator.cpp.i

BackEnd/RegisterAllocator.s: BackEnd/RegisterAllocator.cpp.s

.PHONY : BackEnd/RegisterAllocator.s

# target to generate assembly for a file
BackEnd/RegisterAllocator.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/RegisterAllocator.cpp.s
.PHONY : BackEnd/RegisterAllocator.cpp.s

BackEnd/RiscGenerator.o: BackEnd/RiscGenerator.cpp.o

.PHONY : BackEnd/RiscGenerator.o

# target to build an object file
BackEnd/RiscGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/RiscGenerator.cpp.o
.PHONY : BackEnd/RiscGenerator.cpp.o

BackEnd/RiscGenerator.i: BackEnd/RiscGenerator.cpp.i

.PHONY : BackEnd/RiscGenerator.i

# target to preprocess a source file
BackEnd/RiscGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/RiscGenerator.cpp.i
.PHONY : BackEnd/RiscGenerator.cpp.i

BackEnd/RiscGenerator.s: BackEnd/RiscGenerator.cpp.s

.PHONY : BackEnd/RiscGenerator.s

# target to generate assembly for a file
BackEnd/RiscGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/BackEnd/RiscGenerator.cpp.s
.PHONY : BackEnd/RiscGenerator.cpp.s

compiler.o: compiler.cpp.o

.PHONY : compiler.o

# target to build an object file
compiler.cpp.o:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/compiler.cpp.o
.PHONY : compiler.cpp.o

compiler.i: compiler.cpp.i

.PHONY : compiler.i

# target to preprocess a source file
compiler.cpp.i:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/compiler.cpp.i
.PHONY : compiler.cpp.i

compiler.s: compiler.cpp.s

.PHONY : compiler.s

# target to generate assembly for a file
compiler.cpp.s:
	$(MAKE) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/compiler.cpp.s
.PHONY : compiler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... compiler"
	@echo "... BackEnd/KoopaWalker.o"
	@echo "... BackEnd/KoopaWalker.i"
	@echo "... BackEnd/KoopaWalker.s"
	@echo "... BackEnd/RegisterAllocator.o"
	@echo "... BackEnd/RegisterAllocator.i"
	@echo "... BackEnd/RegisterAllocator.s"
	@echo "... BackEnd/RiscGenerator.o"
	@echo "... BackEnd/RiscGenerator.i"
	@echo "... BackEnd/RiscGenerator.s"
	@echo "... compiler.o"
	@echo "... compiler.i"
	@echo "... compiler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

